name: CI

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, edited, synchronize, ready_for_review, review_requested ]
    branches:
      - 'main'

env:
  SOLUTION_FILE_PATH: ./intermediate/vs2022/workshop.sln
  BUILD_CONFIGURATION: Release

jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-2022

    steps:
    - name: Checkout respository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install cmake
      uses: lukka/get-cmake@latest

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Generate Solution
      shell: cmd
      working-directory: ${{github.workspace}}/engine/tools/scripts
      run: ${{github.workspace}}/engine/tools/scripts/generate_vs2022.bat
      
    - name: Build
      working-directory: ${{github.workspace}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}} /t:Restore,Build
